(set-foreground-color "gray")
(set-background-color "black")
(add-to-list 'default-frame-alist '(font . "DejaVu Sans Mono 16" ))
(set-face-attribute 'default t :font "DejaVu Sans Mono 16" )
(tool-bar-mode -1)
(add-to-list 'default-frame-alist '(fullscreen . maximized))
